/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Clinic */
        post: operations["create_clinic_api_clinics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clinic */
        get: operations["get_clinic_api_clinics__clinic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Clinic */
        patch: operations["update_clinic_api_clinics__clinic_id__patch"];
        trace?: never;
    };
    "/api/clinics/{clinic_id}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day */
        get: operations["day_api_clinics__clinic_id__appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_clinics__clinic_id__appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Doctor */
        post: operations["add_doctor_api_clinics__clinic_id__doctors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors/{doctor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Doctor */
        patch: operations["update_doctor_api_clinics__clinic_id__doctors__doctor_id__patch"];
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors/{doctor_id}/hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Hours */
        put: operations["set_hours_api_clinics__clinic_id__doctors__doctor_id__hours_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Faq */
        post: operations["add_faq_api_clinics__clinic_id__faq_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/faq/{faq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Faq */
        delete: operations["delete_faq_api_clinics__clinic_id__faq__faq_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_clinics__clinic_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_clinics__clinic_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_clinics__clinic_id__members__member_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Slug */
        put: operations["set_slug_api_clinics__clinic_id__slug_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Time Off */
        post: operations["add_time_off_api_clinics__clinic_id__time_off_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/time-off/{time_off_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Time Off */
        delete: operations["delete_time_off_api_clinics__clinic_id__time_off__time_off_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hours/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hour Patterns */
        get: operations["hour_patterns_api_hours_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hours/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description How the receptionist will describe these (unsaved) hours.
         */
        post: operations["preview_api_hours_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Appointment */
        Appointment: {
            /** Doctor Id */
            doctor_id: number;
            /** Doctor Name */
            doctor_name: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Id */
            id: number;
            /** Patient Name */
            patient_name: string;
            /** Patient Phone */
            patient_phone: string;
            /**
             * Source
             * @enum {string}
             */
            source: "voice" | "dashboard";
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "booked" | "cancelled";
        };
        /** Clinic */
        Clinic: {
            /** Address */
            address: string;
            /** Booking Window Days */
            booking_window_days: number;
            /** Call Link */
            call_link: string;
            /** Doctors */
            doctors: components["schemas"]["Doctor"][];
            /** Faq */
            faq: components["schemas"]["Faq"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Slots Offered */
            slots_offered: number;
            /** Slug */
            slug: string;
            /** Time Off */
            time_off: components["schemas"]["TimeOff"][];
            /** Timezone */
            timezone: string;
        };
        /** ClinicDetails */
        ClinicDetails: {
            /**
             * Address
             * @default
             */
            address: string;
            /** Booking Window Days */
            booking_window_days: number;
            /** Name */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /** Slots Offered */
            slots_offered: number;
        };
        /** ClinicSummary */
        ClinicSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** Day */
        Day: {
            /** Appointments */
            appointments: components["schemas"]["Appointment"][];
            /** Booked */
            booked: number;
            /** Booked On Calls */
            booked_on_calls: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Next 7 Days */
            next_7_days: number;
        };
        /** Doctor */
        Doctor: {
            /** Active */
            active: boolean;
            /** Fee */
            fee: number;
            /** Hours */
            hours: components["schemas"]["Sitting"][];
            /** Hours Text */
            hours_text: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slot Minutes */
            slot_minutes: number;
            /** Specialty */
            specialty: string;
        };
        /** DoctorPatch */
        DoctorPatch: {
            /** Active */
            active?: boolean | null;
            /** Fee */
            fee?: number | null;
            /** Name */
            name?: string | null;
            /** Slot Minutes */
            slot_minutes?: number | null;
            /** Specialty */
            specialty?: string | null;
        };
        /** Faq */
        Faq: {
            /** Answer */
            answer: string;
            /** Id */
            id: number;
            /** Question */
            question: string;
        };
        /** FaqIn */
        FaqIn: {
            /** Answer */
            answer: string;
            /** Question */
            question: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoursIn */
        HoursIn: {
            /** Sittings */
            sittings: components["schemas"]["Sitting"][];
        };
        /** HoursText */
        HoursText: {
            /** Text */
            text: string;
        };
        /** Me */
        Me: {
            /** Clinics */
            clinics: components["schemas"]["ClinicSummary"][];
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Login
             * @enum {string}
             */
            login: "google" | "off";
        };
        /** Member */
        Member: {
            /** Email */
            email: string;
            /** Id */
            id: number;
        };
        /** MemberIn */
        MemberIn: {
            /** Email */
            email: string;
        };
        /** NewClinic */
        NewClinic: {
            /**
             * Address
             * @default
             */
            address: string;
            /** Name */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
        };
        /** NewDoctor */
        NewDoctor: {
            /** Fee */
            fee: number;
            /**
             * Hours
             * @default []
             */
            hours: components["schemas"]["Sitting"][];
            /** Name */
            name: string;
            /** Slot Minutes */
            slot_minutes: number;
            /**
             * Specialty
             * @default
             */
            specialty: string;
        };
        /** Pattern */
        Pattern: {
            /** Name */
            name: string;
            /** Sittings */
            sittings: components["schemas"]["Sitting"][];
        };
        /** Sitting */
        Sitting: {
            /**
             * End
             * Format: time
             */
            end: string;
            /**
             * Start
             * Format: time
             */
            start: string;
            /** Weekday */
            weekday: number;
        };
        /** SlugIn */
        SlugIn: {
            /** Slug */
            slug: string;
        };
        /** TimeOff */
        TimeOff: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Doctor Id */
            doctor_id: number | null;
            /** Id */
            id: number;
            /** Reason */
            reason: string;
        };
        /** TimeOffIn */
        TimeOffIn: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Doctor Id */
            doctor_id?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_clinic_api_clinics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClinic"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clinic_api_clinics__clinic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_clinic_api_clinics__clinic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClinicDetails"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    day_api_clinics__clinic_id__appointments_get: {
        parameters: {
            query: {
                day: string;
                include_cancelled?: boolean;
            };
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_clinics__clinic_id__appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_doctor_api_clinics__clinic_id__doctors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDoctor"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_doctor_api_clinics__clinic_id__doctors__doctor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_hours_api_clinics__clinic_id__doctors__doctor_id__hours_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoursIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_faq_api_clinics__clinic_id__faq_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_faq_api_clinics__clinic_id__faq__faq_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_clinics__clinic_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_clinics__clinic_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_clinics__clinic_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_slug_api_clinics__clinic_id__slug_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlugIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_time_off_api_clinics__clinic_id__time_off_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeOffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_time_off_api_clinics__clinic_id__time_off__time_off_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                time_off_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hour_patterns_api_hours_patterns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pattern"][];
                };
            };
        };
    };
    preview_api_hours_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoursIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoursText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
}
