/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calls */
        get: operations["calls_api_admin_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Call Trace */
        get: operations["call_trace_api_admin_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/calls/{call_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Transcript
         * @description Break-glass: the reason is logged (and shown to the clinic) before
         *     the words are returned.
         */
        post: operations["open_transcript_api_admin_calls__call_id__transcript_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinics */
        get: operations["clinics_api_admin_clinics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clinics/{clinic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Clinic
         * @description Irreversible: the clinic must be paused first, and its exact name typed.
         */
        delete: operations["delete_clinic_api_admin_clinics__clinic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clinics/{clinic_id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Active */
        put: operations["set_active_api_admin_clinics__clinic_id__active_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Error Groups */
        get: operations["error_groups_api_admin_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Clinic */
        post: operations["create_clinic_api_clinics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clinic */
        get: operations["get_clinic_api_clinics__clinic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Clinic */
        patch: operations["update_clinic_api_clinics__clinic_id__patch"];
        trace?: never;
    };
    "/api/clinics/{clinic_id}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day */
        get: operations["day_api_clinics__clinic_id__appointments_get"];
        put?: never;
        /** Book */
        post: operations["book_api_clinics__clinic_id__appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change */
        put: operations["change_api_clinics__clinic_id__appointments__appointment_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/appointments/{appointment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_clinics__clinic_id__appointments__appointment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Doctor */
        post: operations["add_doctor_api_clinics__clinic_id__doctors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors/{doctor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Doctor
         * @description Remove a doctor for good (deactivating keeps them). Refused with a
         *     422 while they have upcoming bookings.
         */
        delete: operations["delete_doctor_api_clinics__clinic_id__doctors__doctor_id__delete"];
        options?: never;
        head?: never;
        /** Update Doctor */
        patch: operations["update_doctor_api_clinics__clinic_id__doctors__doctor_id__patch"];
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors/{doctor_id}/free": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Free */
        get: operations["free_api_clinics__clinic_id__doctors__doctor_id__free_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/doctors/{doctor_id}/hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Hours */
        put: operations["set_hours_api_clinics__clinic_id__doctors__doctor_id__hours_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Faq */
        post: operations["add_faq_api_clinics__clinic_id__faq_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/faq/{faq_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Faq */
        delete: operations["delete_faq_api_clinics__clinic_id__faq__faq_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members */
        get: operations["members_api_clinics__clinic_id__members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_api_clinics__clinic_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_clinics__clinic_id__members__member_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Slug */
        put: operations["set_slug_api_clinics__clinic_id__slug_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Time Off
         * @description Leave or a holiday. Bookings already on those days stay booked; they
         *     come back as `clashes` so staff can call those patients.
         */
        post: operations["add_time_off_api_clinics__clinic_id__time_off_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clinics/{clinic_id}/time-off/{time_off_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Time Off */
        delete: operations["delete_time_off_api_clinics__clinic_id__time_off__time_off_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hours/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hour Patterns */
        get: operations["hour_patterns_api_hours_patterns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hours/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description How the receptionist will describe these (unsaved) hours.
         */
        post: operations["preview_api_hours_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveIn */
        ActiveIn: {
            /** Active */
            active: boolean;
        };
        /** AdminClinic */
        AdminClinic: {
            /** Active */
            active: boolean;
            /** Calls 7D */
            calls_7d: number;
            /** Calls With Errors 7D */
            calls_with_errors_7d: number;
            /** Doctors */
            doctors: number;
            /** Id */
            id: number;
            /** Last Call At */
            last_call_at: string | null;
            /** Members */
            members: components["schemas"]["Member"][];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** Appointment */
        Appointment: {
            /** Doctor Id */
            doctor_id: number;
            /** Doctor Name */
            doctor_name: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Id */
            id: number;
            /** Patient Name */
            patient_name: string;
            /** Patient Phone */
            patient_phone: string;
            /** Problem */
            problem?: string | null;
            /** Reason */
            reason: string;
            /**
             * Source
             * @enum {string}
             */
            source: "voice" | "dashboard";
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "booked" | "cancelled";
        };
        /**
         * AppointmentIn
         * @description A booking as staff enter it; also the whole edit form (PUT).
         */
        AppointmentIn: {
            /** Doctor Id */
            doctor_id: number;
            /** Patient Name */
            patient_name: string;
            /** Patient Phone */
            patient_phone: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** Attention */
        Attention: {
            /** Call Id */
            call_id?: number | null;
            /** Clinic Id */
            clinic_id?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "dropped" | "failed" | "errors" | "quiet";
            /** Text */
            text: string;
        };
        /** CallChange */
        CallChange: {
            /**
             * Action
             * @enum {string}
             */
            action: "booked" | "moved" | "cancelled";
            /** Id */
            id: number;
        };
        /** CallSummary */
        CallSummary: {
            /** Appointments */
            appointments: components["schemas"]["CallChange"][];
            /** Clinic Id */
            clinic_id: number;
            /** Clinic Name */
            clinic_name: string;
            /** Duration S */
            duration_s: number | null;
            /** End Reason */
            end_reason: string;
            /** Error Count */
            error_count: number;
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Stack */
            stack: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "ended" | "dropped";
            /** Tool Failures */
            tool_failures: number;
            /** Turn Count */
            turn_count: number;
        };
        /** CallTrace */
        CallTrace: {
            /** Accesses */
            accesses: components["schemas"]["TranscriptAccess"][];
            /** Appointments */
            appointments: components["schemas"]["CallChange"][];
            /** Clinic Id */
            clinic_id: number;
            /** Clinic Name */
            clinic_name: string;
            /** Duration S */
            duration_s: number | null;
            /** End Reason */
            end_reason: string;
            /** Error Count */
            error_count: number;
            /** Events */
            events: components["schemas"]["TraceEvent"][];
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Stack */
            stack: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "ended" | "dropped";
            /** Tool Failures */
            tool_failures: number;
            /** Transcript Kept */
            transcript_kept: boolean;
            /** Turn Count */
            turn_count: number;
        };
        /** Clinic */
        Clinic: {
            /** Address */
            address: string;
            /** Booking Window Days */
            booking_window_days: number;
            /** Call Link */
            call_link: string;
            /** Doctors */
            doctors: components["schemas"]["Doctor"][];
            /** Faq */
            faq: components["schemas"]["Faq"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Slots Offered */
            slots_offered: number;
            /** Slug */
            slug: string;
            /** Time Off */
            time_off: components["schemas"]["TimeOff"][];
            /** Timezone */
            timezone: string;
        };
        /** ClinicDetails */
        ClinicDetails: {
            /**
             * Address
             * @default
             */
            address: string;
            /** Booking Window Days */
            booking_window_days: number;
            /** Name */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /** Slots Offered */
            slots_offered: number;
        };
        /** ClinicSummary */
        ClinicSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Staff */
            staff: boolean;
        };
        /** Day */
        Day: {
            /** Appointments */
            appointments: components["schemas"]["Appointment"][];
            /** Booked */
            booked: number;
            /** Booked On Calls */
            booked_on_calls: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Next 7 Days */
            next_7_days: number;
        };
        /** DeleteClinicIn */
        DeleteClinicIn: {
            /** Confirm Name */
            confirm_name: string;
        };
        /** Doctor */
        Doctor: {
            /** Active */
            active: boolean;
            /** Fee */
            fee: number;
            /** Hours */
            hours: components["schemas"]["Sitting"][];
            /** Hours Text */
            hours_text: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slot Minutes */
            slot_minutes: number;
            /** Specialty */
            specialty: string;
            /** Upcoming */
            upcoming: number;
        };
        /** DoctorPatch */
        DoctorPatch: {
            /** Active */
            active?: boolean | null;
            /** Fee */
            fee?: number | null;
            /** Name */
            name?: string | null;
            /** Slot Minutes */
            slot_minutes?: number | null;
            /** Specialty */
            specialty?: string | null;
        };
        /** ErrorGroup */
        ErrorGroup: {
            /** Call Ids */
            call_ids: number[];
            /** Count */
            count: number;
            /** Detail */
            detail: string;
            /**
             * Last At
             * Format: date-time
             */
            last_at: string;
            /** Name */
            name: string;
        };
        /** Faq */
        Faq: {
            /** Answer */
            answer: string;
            /** Id */
            id: number;
            /** Question */
            question: string;
        };
        /** FaqIn */
        FaqIn: {
            /** Answer */
            answer: string;
            /** Question */
            question: string;
        };
        /** FreeTimes */
        FreeTimes: {
            /** Times */
            times: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Attention */
            attention: components["schemas"]["Attention"][];
            /** Calls */
            calls: number;
            /** Calls Today */
            calls_today: number;
            /** Days */
            days: number;
            /** Dropped */
            dropped: number;
            /** Outcomes */
            outcomes: {
                [key: string]: number;
            };
            /** Stages */
            stages: components["schemas"]["Stage"][];
            /** Vendors */
            vendors: components["schemas"]["VendorErrors"][];
            /** With Errors */
            with_errors: number;
        };
        /** HoursIn */
        HoursIn: {
            /** Sittings */
            sittings: components["schemas"]["Sitting"][];
        };
        /** HoursText */
        HoursText: {
            /** Text */
            text: string;
        };
        /** Me */
        Me: {
            /** Clinics */
            clinics: components["schemas"]["ClinicSummary"][];
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Login
             * @enum {string}
             */
            login: "google" | "off";
        };
        /** Member */
        Member: {
            /** Email */
            email: string;
            /** Id */
            id: number;
        };
        /** MemberIn */
        MemberIn: {
            /** Email */
            email: string;
        };
        /** NewClinic */
        NewClinic: {
            /**
             * Address
             * @default
             */
            address: string;
            /** Name */
            name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
        };
        /** NewDoctor */
        NewDoctor: {
            /** Fee */
            fee: number;
            /**
             * Hours
             * @default []
             */
            hours: components["schemas"]["Sitting"][];
            /** Name */
            name: string;
            /** Slot Minutes */
            slot_minutes: number;
            /**
             * Specialty
             * @default
             */
            specialty: string;
        };
        /** Pattern */
        Pattern: {
            /** Name */
            name: string;
            /** Sittings */
            sittings: components["schemas"]["Sitting"][];
        };
        /** Sitting */
        Sitting: {
            /**
             * End
             * Format: time
             */
            end: string;
            /**
             * Start
             * Format: time
             */
            start: string;
            /** Weekday */
            weekday: number;
        };
        /** SlugIn */
        SlugIn: {
            /** Slug */
            slug: string;
        };
        /** Stage */
        Stage: {
            /** Count */
            count: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Stack */
            stack: string;
            /** Stage */
            stage: string;
        };
        /** TimeOff */
        TimeOff: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Doctor Id */
            doctor_id: number | null;
            /** Id */
            id: number;
            /** Reason */
            reason: string;
        };
        /** TimeOffAdded */
        TimeOffAdded: {
            /** Clashes */
            clashes: components["schemas"]["Appointment"][];
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Doctor Id */
            doctor_id: number | null;
            /** Id */
            id: number;
            /** Reason */
            reason: string;
        };
        /** TimeOffIn */
        TimeOffIn: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Doctor Id */
            doctor_id?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** TraceEvent */
        TraceEvent: {
            /** Detail */
            detail: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** T Ms */
            t_ms: number;
        };
        /** TranscriptAccess */
        TranscriptAccess: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Email */
            email: string;
            /** Reason */
            reason: string;
        };
        /** TranscriptItem */
        TranscriptItem: {
            /** Args */
            args?: string | null;
            /**
             * Interrupted
             * @default false
             */
            interrupted: boolean;
            /** Ok */
            ok?: boolean | null;
            /**
             * Role
             * @enum {string}
             */
            role: "caller" | "agent" | "tool" | "error";
            /** T Ms */
            t_ms: number;
            /** Text */
            text: string;
            /** Tool */
            tool?: string | null;
        };
        /** TranscriptReason */
        TranscriptReason: {
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VendorErrors */
        VendorErrors: {
            /** Calls */
            calls: number;
            /** Errors */
            errors: number;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calls_api_admin_calls_get: {
        parameters: {
            query?: {
                clinic_id?: number | null;
                outcome?: string | null;
                status?: string | null;
                with_errors?: boolean;
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    call_trace_api_admin_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_transcript_api_admin_calls__call_id__transcript_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptReason"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clinics_api_admin_clinics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinic"][];
                };
            };
        };
    };
    delete_clinic_api_admin_clinics__clinic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteClinicIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_api_admin_clinics__clinic_id__active_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActiveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminClinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    error_groups_api_admin_errors_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_admin_health_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_clinic_api_clinics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClinic"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clinic_api_clinics__clinic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_clinic_api_clinics__clinic_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClinicDetails"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    day_api_clinics__clinic_id__appointments_get: {
        parameters: {
            query: {
                day: string;
                include_cancelled?: boolean;
            };
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Day"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_api_clinics__clinic_id__appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_api_clinics__clinic_id__appointments__appointment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_clinics__clinic_id__appointments__appointment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_doctor_api_clinics__clinic_id__doctors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDoctor"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_doctor_api_clinics__clinic_id__doctors__doctor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_doctor_api_clinics__clinic_id__doctors__doctor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    free_api_clinics__clinic_id__doctors__doctor_id__free_get: {
        parameters: {
            query: {
                day: string;
            };
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeTimes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_hours_api_clinics__clinic_id__doctors__doctor_id__hours_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoursIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doctor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_faq_api_clinics__clinic_id__faq_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaqIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Faq"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_faq_api_clinics__clinic_id__faq__faq_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                faq_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    members_api_clinics__clinic_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_clinics__clinic_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_clinics__clinic_id__members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_slug_api_clinics__clinic_id__slug_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlugIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_time_off_api_clinics__clinic_id__time_off_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeOffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffAdded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_time_off_api_clinics__clinic_id__time_off__time_off_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                time_off_id: number;
                clinic_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hour_patterns_api_hours_patterns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pattern"][];
                };
            };
        };
    };
    preview_api_hours_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoursIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoursText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
}
