"""call records

Revision ID: 0005
Revises: 0004
Created: 2026-09-26 19:21:17.556010
"""

from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('stack', sa.String(length=300), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('appointments', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_calls_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_clinic_id_started_at', ['clinic_id', 'started_at'], unique=False)

    op.create_table('call_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('t_ms', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_events_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events'))
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_events_call_id'), ['call_id'], unique=False)

    op.create_table('call_transcripts',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('purge_after', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_transcripts_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id', name=op.f('pk_call_transcripts'))
    )
    op.create_table('transcript_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_transcript_access_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_transcript_access_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_access'))
    )
    with op.batch_alter_table('transcript_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_access_call_id'), ['call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_access_call_id'))

    op.drop_table('transcript_access')
    op.drop_table('call_transcripts')
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_call_id'))

    op.drop_table('call_events')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index('ix_calls_clinic_id_started_at')

    op.drop_table('calls')
    # ### end Alembic commands ###
