"""health incidents

Revision ID: 0008
Revises: 0007
Created: 2026-09-28 13:56:19.901570
"""

from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats')),
    sa.UniqueConstraint('worker', name=op.f('uq_worker_heartbeats_worker'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('seen_by_clinic_at', sa.DateTime(), nullable=True),
    sa.Column('seen_by_admin_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_incidents_clinic_id_clinics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_clinic_id_opened_at', ['clinic_id', 'opened_at'], unique=False)
        batch_op.create_index('uq_incident_open', ['key'], unique=True, sqlite_where=sa.text('resolved_at IS NULL'), postgresql_where=sa.text('resolved_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_incident_open', sqlite_where=sa.text('resolved_at IS NULL'), postgresql_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index('ix_incidents_clinic_id_opened_at')

    op.drop_table('incidents')
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
